# Generated by Django 5.2.10 on 2026-05-21 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documents', serialize=False, to='main_system.company')),
                ('authorized_by', models.CharField(blank=True, max_length=200, null=True)),
                ('business_purpose', models.TextField(blank=True, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='company_documents/signatures/')),
                ('stamp', models.FileField(blank=True, null=True, upload_to='company_documents/stamps/')),
                ('official_request_letter', models.FileField(blank=True, null=True, upload_to='company_documents/letters/')),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
                'db_table': 'copo_company_documents',
                'permissions': [('view_company_documents', 'Can view company documents')],
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='blank_col1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='blank_col2',
        ),
        migrations.AddField(
            model_name='company',
            name='blankcol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_person_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
