# Generated by Django 6.0 on 2026-01-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='blank_col1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='blank_col2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
