# Generated by Django 6.0 on 2026-01-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
