# Generated by Django 5.2.10 on 2026-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0002_companydocument_remove_company_blank_col1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'permissions': [('soft_delete_company_account', 'Can soft delete company account'), ('reset_company_account_password', 'Can reset company account passwords'), ('approve_company_account', 'Can approve company account')]},
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
