# Generated by Django 5.2.10 on 2026-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0003_alter_companyaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
