# Generated by Django 6.0 on 2026-01-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0002_company_blank_col1_company_blank_col2_and_more'),
        ('main_system', '0003_auto_20260113_1228'),
    ]

    operations = [
    ]
