# Generated by Django 5.2.10 on 2026-09-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0004_company_company_code_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='technical_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='technical_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='technical_person_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
