# Generated by Django 6.0 on 2026-01-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0004_merge_20260113_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='main_system.individual')),
            ],
            options={
                'db_table': 'policy',
            },
        ),
    ]
