# Generated by Django 5.2.10 on 2026-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0005_company_technical_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('timeout_until', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Lockout',
                'verbose_name_plural': 'Account Lockouts',
                'db_table': 'copo_account_lockout',
            },
        ),
        migrations.AlterField(
            model_name='reportaccesslog',
            name='report_type',
            field=models.CharField(db_index=True, help_text="Report's name.", max_length=150),
        ),
    ]
