# Generated by Django 6.0 on 2026-01-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0005_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_own_account', 'Can view own account details'), ('reset_staff_password', 'Can reset staff passwords')]},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('soft_delete_company', 'Can soft delete company')]},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('soft_delete_group', 'Can soft delete group')]},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'permissions': [('soft_delete_individual', 'Can soft delete individual'), ('reset_individual_password', 'Can reset individual passwords')]},
        ),
    ]
