# Generated by Django 5.2.10 on 2026-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0006_alter_account_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('password_reset', 'Password Reset'), ('role_change', 'Role Change'), ('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete'), ('create', 'Create'), ('update', 'Update')], max_length=50)),
                ('target_username', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=50)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
