# Generated by Django 5.2.10 on 2026-01-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('role_change', 'Role Change'), ('soft_delete', 'Soft Delete'), ('hard_delete', 'Hard Delete'), ('create', 'Create'), ('update', 'Update'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('permission_change', 'Permission Change')], max_length=50),
        ),
    ]
