# Generated by Django 5.2.10 on 2026-03-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0008_auditlog_ip_address_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='copo_account',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='copo_audit_log',
        ),
        migrations.AlterModelTable(
            name='company',
            table='copo_company',
        ),
        migrations.AlterModelTable(
            name='group',
            table='copo_groups',
        ),
        migrations.AlterModelTable(
            name='individual',
            table='copo_individual',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='copo_policy',
        ),
    ]
