# Generated by Django 5.2.10 on 2026-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0009_alter_account_table_alter_auditlog_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username of the user who triggered the report.', max_length=150)),
                ('report_type', models.CharField(db_index=True, help_text="Human-readable report name. e.g. 'Maturity Forecasting Report', 'Death Claim Report'.", max_length=150)),
                ('target_type', models.CharField(choices=[('group', 'Group'), ('policy', 'Policy')], db_index=True, help_text='Whether the report targets a group or a policy.', max_length=10)),
                ('target_id', models.CharField(db_index=True, help_text='The ID of the target — either a group_id or a policy_no depending on target_type.', max_length=100)),
                ('parameters', models.JSONField(default=dict, help_text='All input parameters sent with the request stored as a JSON blob (dates, flags, etc.).')),
                ('status', models.CharField(choices=[('success', 'Success'), ('no_data', 'No Data'), ('error', 'Error'), ('forbidden', 'Forbidden'), ('invalid_input', 'Invalid Input')], db_index=True, help_text='Outcome of the report request.', max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of when the report was requested.')),
            ],
            options={
                'verbose_name': 'Report Access Log',
                'verbose_name_plural': 'Report Access Logs',
                'db_table': 'copo_error_log',
                'ordering': ['-generated_at'],
            },
        ),
    ]
