# Generated by Django 5.2.10 on 2026-04-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0010_reportaccesslog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportaccesslog',
            table='copo_report_generation_log',
        ),
    ]
