# Generated by Django 5.2.10 on 2026-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0011_alter_reportaccesslog_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportaccesslog',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Report Generation Log', 'verbose_name_plural': 'Report Generation Logs'},
        ),
        migrations.RenameField(
            model_name='reportaccesslog',
            old_name='report_id',
            new_name='row_id',
        ),
        migrations.RemoveField(
            model_name='reportaccesslog',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='reportaccesslog',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='reportaccesslog',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='reportaccesslog',
            name='username',
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Full error message or traceback captured on failure. NULL on success.', null=True),
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='generator_company',
            field=models.CharField(default='unknown', help_text='Username of the company user who triggered the report.', max_length=150),
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='query',
            field=models.TextField(default='N/A', help_text='Raw SQL query with injected parameters exactly as executed against the database.'),
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional free-form notes for any additional context.', null=True),
        ),
        migrations.AlterField(
            model_name='reportaccesslog',
            name='report_type',
            field=models.CharField(db_index=True, help_text="Human-readable report name. e.g. 'Death Claim Report', 'Maturity Forecasting Report'.", max_length=150),
        ),
    ]
