# Generated by Django 5.2.10 on 2026-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0012_alter_reportaccesslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaccesslog',
            name='has_error',
            field=models.BooleanField(default=False, help_text='1 if error exists, 0 if no error.'),
        ),
    ]
