# Generated by Django 5.2.10 on 2026-04-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0013_reportaccesslog_has_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Company Account',
                'verbose_name_plural': 'Company Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_system.account',),
        ),
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='main_system.company'),
        ),
    ]
