# Generated by Django 5.2.10 on 2026-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('row_id', models.BigAutoField(db_column='RowId', primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, db_column='GroupName', max_length=50, null=True)),
                ('group_name_nepali', models.CharField(blank=True, db_column='GroupNameNepali', max_length=50, null=True)),
                ('discount_rate', models.DecimalField(blank=True, db_column='DiscountRate', decimal_places=4, max_digits=19, null=True)),
                ('fiscal_year', models.CharField(blank=True, db_column='FiscalYear', max_length=50, null=True)),
                ('short_name', models.CharField(blank=True, db_column='ShortName', max_length=50, null=True)),
                ('master_policy_no', models.CharField(blank=True, db_column='MasterPolicyNo', max_length=50, null=True)),
                ('group_id', models.CharField(blank=True, db_column='GroupId', max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('group_type', models.CharField(blank=True, db_column='GroupType', max_length=100, null=True)),
                ('account_number', models.BigIntegerField(blank=True, db_column='AccountNumber', null=True)),
                ('p_seq', models.CharField(blank=True, db_column='PSeq', max_length=50, null=True)),
                ('g_seq', models.CharField(blank=True, db_column='Gseq', max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, db_column='ModifiedBy', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('r_seq', models.IntegerField(blank=True, db_column='RSeq', null=True)),
                ('plan_id', models.IntegerField(blank=True, db_column='PlanID', null=True)),
                ('adb_discount_rate', models.DecimalField(blank=True, db_column='ADBDiscountRate', decimal_places=4, max_digits=19, null=True)),
                ('retirement_age', models.IntegerField(blank=True, db_column='RetirementAge', null=True)),
                ('min_age', models.BigIntegerField(blank=True, db_column='MinAge', null=True)),
                ('max_age', models.BigIntegerField(blank=True, db_column='MaxAge', null=True)),
                ('min_term', models.BigIntegerField(blank=True, db_column='MinTerm', null=True)),
                ('max_term', models.BigIntegerField(blank=True, db_column='MaxTerm', null=True)),
                ('rebate', models.IntegerField(blank=True, db_column='Rebate', null=True)),
                ('p2_seq', models.BigIntegerField(blank=True, db_column='P2Seq', null=True)),
                ('doc', models.DateTimeField(blank=True, db_column='DOC', null=True)),
                ('g_loan', models.CharField(blank=True, db_column='G_LOAN', max_length=10, null=True)),
                ('s_policy', models.CharField(blank=True, db_column='S_Policy', max_length=50, null=True)),
                ('adb_amount', models.DecimalField(blank=True, db_column='ADBAmount', decimal_places=4, max_digits=19, null=True)),
                ('extra_premium', models.DecimalField(blank=True, db_column='ExtraPremium', decimal_places=4, max_digits=19, null=True)),
                ('mode', models.CharField(blank=True, db_column='Mode', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=50, null=True)),
                ('adb_rate', models.DecimalField(blank=True, db_column='ADBRate', decimal_places=4, max_digits=19, null=True)),
                ('extra_load', models.DecimalField(blank=True, db_column='ExtraLoad', decimal_places=4, max_digits=19, null=True)),
                ('is_adb', models.CharField(blank=True, db_column='IsADB', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblGroupInformation',
                'ordering': ['-created_date'],
                'managed': False,
            },
        ),
    ]
