# Generated by Django 5.2.10 on 2026-01-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_corporate', '0002_groupendowment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupendowment',
            options={'managed': False, 'ordering': ['-maturity_date']},
        ),
        migrations.AlterModelTable(
            name='groupendowment',
            table='view_copo_groupEndowment',
        ),
    ]
