# Generated by Django 5.2.10 on 2026-03-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_corporate', '0003_alter_groupendowment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinformation',
            options={'managed': False, 'ordering': ['group_id']},
        ),
        migrations.AlterModelTable(
            name='groupinformation',
            table='view_copo_groupInformation',
        ),
    ]
